### ISSUE TITLE
来亿点奇奇怪怪的东西

### ISSUE THREAD

**Issue by crazy-piggy** [squid233/squid233#1]
我现在电脑登不了QQ QAQ
所以在这里开一个Issue awa
你试试能不能建一个代码库，里面放你的模组的框架（类似 https://github.com/FabricMC/fabric-example-mod ）
我想做一个fabric模组懒人开发程序😏具体内容请看 https://github.com/crazy-piggy/FabricModEasyDevelopmentProgram

**Comment by squid233** [comment]
e
